### ISSUE TITLE
Very first example does not work

### ISSUE THREAD

**Issue by rwrife** [MicrosoftDocs/azure-docs-cli#1389] opened 2019-04-04 21:15 UTC
"az find -q secret" -q is not a valid argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2019-04-08 23:15
Thanks for the report, this is a duplicate of #1363 and will be closed. Follow that issue for updates.

**Closed by sptramer** 2019-04-08 23:15 UTC
Labels: doc-bug, duplicate, triaged

**Comment by sptramer** [comment] 2019-04-09 17:49
This should be fixed in today's publish.

**Comment by garybushey** [comment] 2019-04-10 18:28
Not sure what happened but now "az find" requires "-q" so the original entry was correct

**Comment by sptramer** [comment] 2019-04-10 23:28
Just checked with azure CLI 2.0.62 - the `-q` argument is definitely not required, so `az find` should work as described here.
