### ISSUE TITLE
cannot find way to install python36 dependency

### ISSUE THREAD

**Issue by pmozbert** [MicrosoftDocs/azure-docs-cli#1815] opened 2020-02-20 01:46 UTC
I'm trying to find a way to install python36 on a RHEL 3.6 VM (publish RedHat, offer RHEL, sku 7.6, version latest), but can't find a way to do it aside from building from source.  Can you link to instructions that have been tested and are known to work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f55d23-7802-e0da-6d12-b71f6da8a1d4
* Version Independent ID: 192846d7-baae-bcba-698b-22bdcdae468a
* Content: [Install the Azure CLI on Linux with yum](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-yum.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-yum.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment] 2020-02-20 05:44
@pmozbert Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by pmozbert** [comment] 2020-02-21 01:56
Thanks.  I'm using packer to create custom images and am trying to bake in some basic utilites like the azure cli.   The most recent package for python that i can find to install with yum on RHEL is 3.4.

**Comment by asinn826** [comment] 2020-02-21 19:19
@pmozbert - Which commands are you running? The steps here worked for me: https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/

I ran `yum -y install rh-python36` and then `scl enable rh-python36 bash` on a RHEL 7.6 VM (RedHat:RHEL:7.6:7.6.2019102813)

**Comment by pmozbert** [comment] 2020-02-21 20:47
I believe you need to be logged in to a RH subscription in order to install rh-* and to use scl.  But I'm using Packer to run commands on the vm when creating custom image.  How would I do it in that case?

**Comment by SamaraSoucy-MSFT** [comment] 2020-02-25 20:38
@pmozbert I found an example that includes logging into and out of a RH subscription inside a Packer script: [https://github.com/ansiblejunky/packer-rhel](https://github.com/ansiblejunky/packer-rhel )

Is that something you could incorporate into your own scripts?

**Comment by pmozbert** [comment] 2020-02-26 22:07
Hi, I was able to install python 3.6 from RHN by following the RHN registration example in [https://github.com/ansiblejunky/packer-rhel](https://github.com/ansiblejunky/packer-rhel)  but I'm still having problems.

summary
```
Error: Package: azure-cli-2.1.0-1.el7.x86_64 (azure-cli)
           Requires: libpython3.6m.so.1.0()(64bit)
Error: Package: azure-cli-2.1.0-1.el7.x86_64 (azure-cli)
           Requires: python3
```

I verified that I can use python 3 like this
```
[ ~]$ scl enable rh-python36 'python --version'
Python 3.6.9
```
The script called from Packer does this
```
echo '==> Installing Azure CLI'
# add a symlink because azurecli seems to want it
pushd /opt/rh/rh-python36/root/usr/lib64
ln -s libpython3.6m.so.rh-python36-1.0 libpython3.6m.so.1.0
echo '==> folder /opt/rh/rh-python36/root/usr/lib64'
ls -al
popd
echo '==> folder /opt/rh/rh-python36/root/usr/bin'
ls -al /opt/rh/rh-python36/root/usr/bin
scl enable rh-python36 'python --version;which python3;yum install -y -v azure-cli'
echo '==> Finished install of Azure CLI'
```
And this is the output from the above
```
==> Installing Azure CLI
/opt/rh/rh-python36/root/usr/lib64 ~/packer-temp
==> folder /opt/rh/rh-python36/root/usr/lib64
total 3088
dr-xr-xr-x.  9 root root     228 Feb 26 21:10 .
drwxr-xr-x. 13 root root     155 Feb 26 21:10 ..
dr-xr-xr-x.  2 root root       6 May 31  2017 games
lrwxrwxrwx.  1 root root      32 Feb 26 21:10 libpython3.6m.so -> libpython3.6m.so.rh-python36-1.0
lrwxrwxrwx.  1 root root      32 Feb 26 21:10 libpython3.6m.so.1.0 -> libpython3.6m.so.rh-python36-1.0
-rwxr-xr-x.  1 root root 3140368 Sep 11 20:43 libpython3.6m.so.rh-python36-1.0
-rwxr-xr-x.  1 root root    6696 Sep 11 20:43 libpython3.so.rh-python36
drwxr-xr-x.  2 root root      84 Feb 26 21:10 pkgconfig
dr-xr-xr-x.  5 root root      52 Feb 26 21:10 pm-utils
drwxr-xr-x. 37 root root    8192 Feb 26 21:10 python3.6
dr-xr-xr-x.  2 root root       6 May 31  2017 sse2
dr-xr-xr-x.  2 root root       6 May 31  2017 tls
dr-xr-xr-x.  2 root root       6 May 31  2017 X11
~/packer-temp
==> folder /opt/rh/rh-python36/root/usr/bin
total 92
dr-xr-xr-x.  2 root root  4096 Feb 26 21:10 .
drwxr-xr-x. 13 root root   155 Feb 26 21:10 ..
lrwxrwxrwx.  1 root root     8 Feb 26 21:10 2to3 -> 2to3-3.6
-rwxr-xr-x.  1 root root   119 Sep 11 20:41 2to3-3.6
-rwxr-xr-x.  1 root root   258 Sep 25  2017 easy_install
-rwxr-xr-x.  1 root root   258 Sep 25  2017 easy_install-3.6
-rwxr-xr-x.  1 root root   782 Sep 25  2017 f2py3
lrwxrwxrwx.  1 root root     5 Feb 26 21:10 idle -> idle3
lrwxrwxrwx.  1 root root     7 Feb 26 21:10 idle3 -> idle3.6
-rwxr-xr-x.  1 root root   117 Sep 11 20:41 idle3.6
-rwxr-xr-x.  1 root root   401 Jun 20  2017 nosetests
-rwxr-xr-x.  1 root root   409 Jun 20  2017 nosetests-3.6
-rwxr-xr-x.  1 root root   230 Jun 14  2017 pip
-rwxr-xr-x.  1 root root   230 Jun 14  2017 pip3
-rwxr-xr-x.  1 root root   230 Jun 14  2017 pip3.6
lrwxrwxrwx.  1 root root     6 Feb 26 21:10 pydoc -> pydoc3
lrwxrwxrwx.  1 root root     8 Feb 26 21:10 pydoc3 -> pydoc3.6
-rwxr-xr-x.  1 root root   102 Sep 11 20:41 pydoc3.6
-rwxr-xr-x.  1 root root    82 Sep 11 20:41 pynche
lrwxrwxrwx.  1 root root     7 Feb 26 21:10 python -> python3
lrwxrwxrwx.  1 root root    12 Feb 26 21:10 python-2to3 -> python3-2to3
lrwxrwxrwx.  1 root root     9 Feb 26 21:10 python3 -> python3.6
lrwxrwxrwx.  1 root root    37 Feb 26 21:10 python3-2to3 -> /opt/rh/rh-python36/root/usr/bin/2to3
-rwxr-xr-x.  2 root root 11304 Sep 11 20:43 python3.6
lrwxrwxrwx.  1 root root    17 Feb 26 21:10 python3.6-config -> python3.6m-config
-rwxr-xr-x.  2 root root 11304 Sep 11 20:43 python3.6m
-rwxr-xr-x.  1 root root   173 Sep 11 20:42 python3.6m-config
-rwxr-xr-x.  1 root root  3570 Sep 11 20:21 python3.6m-x86_64-config
lrwxrwxrwx.  1 root root    16 Feb 26 21:10 python3-config -> python3.6-config
lrwxrwxrwx.  1 root root    14 Feb 26 21:10 python-config -> python3-config
lrwxrwxrwx.  1 root root    10 Feb 26 21:10 pyvenv -> pyvenv-3.6
-rwxr-xr-x.  1 root root   459 Sep 11 20:41 pyvenv-3.6
-rwxr-xr-x.  1 root root   424 Jul 27  2017 virtualenv
Python 3.6.9
/opt/rh/rh-python36/root/usr/bin/python3
Not loading "rhnplugin" plugin, as it is disabled
Loading "langpacks" plugin
Loading "product-id" plugin
Loading "search-disabled-repos" plugin
Loading "subscription-manager" plugin
Adding en_US.UTF-8 to language list
Updating Subscription Management repositories.
Config time: 1.889
Yum version: 3.4.3
rpmdb time: 0.000
Setting up Package Sacks
pkgsack time: 0.040
Obs Init time: 0.988
Resolving Dependencies
--> Running transaction check
---> Package azure-cli.x86_64 0:2.1.0-1.el7 will be installed
Checking deps for azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('ld-linux-x86-64.so.2()(64bit)', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('python3', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('rtld(GNU_HASH)', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('libc.so.6(GLIBC_2.4)(64bit)', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('libpthread.so.0(GLIBC_2.2.5)(64bit)', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('libpthread.so.0()(64bit)', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
looking for ('libpython3.6m.so.1.0()(64bit)', None, (None, None, None)) as a requirement of azure-cli.x86_64 0:2.1.0-1.el7 - u
azure-cli-2.1.0-1.el7.x86_64 requires: python3
--> Processing Dependency: python3 for package: azure-cli-2.1.0-1.el7.x86_64
Searching pkgSack for dep: python3
azure-cli-2.1.0-1.el7.x86_64 requires: libpython3.6m.so.1.0()(64bit)
--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: azure-cli-2.1.0-1.el7.x86_64
Searching pkgSack for dep: libpython3.6m.so.1.0()(64bit)
--> Finished Dependency Resolution
Dependency Process ending
Error: Package: azure-cli-2.1.0-1.el7.x86_64 (azure-cli)
           Requires: libpython3.6m.so.1.0()(64bit)
Error: Package: azure-cli-2.1.0-1.el7.x86_64 (azure-cli)
           Requires: python3
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Depsolve time: 0.412
Error: Package: azure-cli-2.1.0-1.el7.x86_64 (azure-cli)
           Requires: libpython3.6m.so.1.0()(64bit)
Error: Package: azure-cli-2.1.0-1.el7.x86_64 (azure-cli)
           Requires: python3
 You could try using --skip-broken to work around the problem
  You could try running: rpm -Va --nofiles --nodigest
==> Finished install of Azure CLI
```
This is what I find on the machine
```
[ ~]$ sudo find / -name libpython3*
/opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so.rh-python36-1.0
/opt/rh/rh-python36/root/usr/lib64/libpython3.so.rh-python36
/opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so
/opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so.1.0
```
libs
```
[ ~]$ ls -l /opt/rh/rh-python36/root/usr/lib64
total 3088
dr-xr-xr-x.  2 root root       6 May 31  2017 games
lrwxrwxrwx.  1 root root      32 Feb 26 21:10 libpython3.6m.so -> libpython3.6m.so.rh-python36-1.0
lrwxrwxrwx.  1 root root      32 Feb 26 21:10 libpython3.6m.so.1.0 -> libpython3.6m.so.rh-python36-1.0
-rwxr-xr-x.  1 root root 3140368 Sep 11 20:43 libpython3.6m.so.rh-python36-1.0
-rwxr-xr-x.  1 root root    6696 Sep 11 20:43 libpython3.so.rh-python36
drwxr-xr-x.  2 root root      84 Feb 26 21:10 pkgconfig
dr-xr-xr-x.  5 root root      52 Feb 26 21:10 pm-utils
drwxr-xr-x. 37 root root    8192 Feb 26 21:10 python3.6
dr-xr-xr-x.  2 root root       6 May 31  2017 sse2
dr-xr-xr-x.  2 root root       6 May 31  2017 tls
dr-xr-xr-x.  2 root root       6 May 31  2017 X11
```
python
```
[ ~]$ sudo scl enable rh-python36 'which python3'
/opt/rh/rh-python36/root/usr/bin/python3
[ ~]$ ls -l /opt/rh/rh-python36/root/usr/bin/python3
lrwxrwxrwx. 1 root root 9 Feb 26 18:49 /opt/rh/rh-python36/root/usr/bin/python3 -> python3.6
```

**Comment by SamaraSoucy-MSFT** [comment] 2020-02-27 03:16
@pmozbert I will continue to work with you on this issue, but because the problem isn't docs related, I'm going to close it. You should still be able to comment here, or if you would prefer, you can send an email to azcommunity(at)microsoft.com with a link to this thread and we can continue there.

**Closed by SamaraSoucy-MSFT** 2020-02-27 03:16 UTC
Labels: Pri1, azure-cli/tech, azure/prod, cxp, doc-enhancement, in-progress, triaged

**Comment by pmozbert** [comment] 2020-02-27 13:43
Your doc states that python 3.6 is a prerequisite, without offering a way to satisfy this prerequisite.  Instructions for installing the CLI on Linux ought to work.  Have you verified that azure CLI can be installed on any of your Linux base image types?

**Comment by lamek** [comment] 2020-02-27 16:18
I followed these instructions to install python 3 (although I think I already had it because python3 -V worked.
https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/#tldr

Yum still wouldn't work, but I was then able to manually download and install the azure-cli with some yum tools I had not heard of.
https://github.com/Azure/azure-cli/issues/11418

**Comment by pmozbert** [comment] 2020-02-27 17:41
Hi, the 11418 ticket you reference doesn't actually give a resolution, though they closed it as resolved. 
Taking a guess here, but is this the thing you did?
```
$ sudo yum install yum-utils
$ sudo yumdownloader azure-cli
$ sudo rpm -ivh --nodeps azure-cli-2.0.77-1.el7.x86_64.rpm
```

**Comment by lamek** [comment] 2020-02-27 18:44
@pmozbert yes, those are the steps I followed. Re-reading this ticket I'm not sure if you can automate those commands in packer or not. Also, I'm on a RHEL 7 laptop with a subscription, but I did already have python3 installed, I think the output from yum just made me assume I didn't.

**Comment by pmozbert** [comment] 2020-02-27 20:44
I got this to work.  for the azure CLI i did this
```
yum install -y yum-utils
yumdownloader azure-cli
therpm=`ls azure-cli-*.rpm`
rpm -ivh --nodeps $therpm
```
but then the cli doesn't just work as-is.  
```
[ ~]$ az help
/usr/bin/az: line 2: python3: command not found
```
you need to go into the RH python3 collection first
```
[ ~]$ scl enable rh-python36 bash
[ ~]$ az help

Group
    az

Subgroups:
    account                     : Manage Azure subscription information.
    acr                         : Manage private registries with Azure Container Registries.
    ad                          : Manage Azure Active Directory Graph entities needed for Role Based
....
```
so there's considerable finesse involved to get Azure CLI to work on RHEL. 
1. you need to log in to a RHN subscription in order to install python 3.6
2. you need to run special commands to install the Azure CLI RPM
3. you need to use scl to go into a python3 environment before you can use the CLI

**Comment by SamaraSoucy-MSFT** [comment] 2020-02-27 22:32
@pmozbert It sounds like you have gotten this working, can you confirm whether or not this is the case?

Unfortunately, we can't test or document how to use the CLI for every version of Linux or every scenario. In this case, the `yum` installation instructions were verified with RHEL 7.7, RHEL 8, Fedora 24+, CentOS 7 and CentOS 8.

We do try to assist with scenarios not expressly defined in the docs and update them appropriately. In the case of [Azure/azure-cli#11418](https://github.com/Azure/azure-cli/issues/11418), 25 minutes after posting about the `python3: command not found` error, the original requester came back and stated they had resolved the issue and closed the thread. Because the requester choose to close the issue, it wasn't addressed further in that thread, but the product team member added the additional information from it to the documentation: https://github.com/MicrosoftDocs/azure-docs-cli/commit/2520ed2607b9a83f9fd1105431041db9fe3be79a

I've put in a PR to add the `scl enable rh-python36 bash` to the [troubleshooting section](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest#troubleshooting) for RHEL 7.6. It's mentioned in the [RedHat post](https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/) linked from the documentation, but we need to add some additional clarity there if it is tripping people up.
