### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by julienmongin-hcl** [MicrosoftDocs/azure-docs-cli#1235] opened 2019-01-09 14:55 UTC
Hi, 

can you confirm if "az login" is working behind a proxy (on windows)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2019-01-22 19:22
This is a duplicate of #965. Unfortunately I've been backlogged on some other tasks but telling users how to work with proxies for the CLI is a priority. For now, follow any instructions from your system administrator for setting up a proxy on your client.

**Closed by sptramer** 2019-01-22 19:22 UTC

**Comment by sptramer** [comment] 2019-05-29 00:27
Possibly resolved by #1471. Not all required endpoints have been catalogued and are unlikely to be, but setting the proxy correctly for your OS will allow connections.
