### ISSUE TITLE
az vm image list errors out if it sees Symantec.test.ru4mp1.latest

### ISSUE THREAD

**Issue by MrBill2U** [MicrosoftDocs/azure-docs-cli#1732] opened 2020-01-03 13:58 UTC
When issuing the following command the list of images is not returned due to an error with Symantec.test.ru4mp1.latest.

```
az vm image list --offer UbuntuServer --all --location eastus2  --output table
Publisher: Symantec.test.ru4mp1.latest was not found.
```

This is preventing Terraform from creating VMs in eastus2.  The Terraform error returned is:

`'Error message: 'The Publisher: Canonical does not make available Offer: UbuntuServer, Plan: 18.04-LTS in your Subscription/Azure account’s region: US.''`

Edit:  In looking around this appears to be a repo for documentation.  I opened this issue for a problem with az cli because I was instructed to by Microsoft employee Jose Rivera in ticket 120010224003368.  I apologize if this is not the proper place to raise a defect in az cli.

**Comment by SamaraSoucy-MSFT** [comment] 2020-01-03 15:51
Thank you for reporting this issue. This forum is indeed for the docs only. The CLI repo can be found here: https://github.com/Azure/azure-cli

I'll reach out to the product team and the engineer assigned to your support case and see if we can find a solution for you.

**Comment by SamaraSoucy-MSFT** [comment] 2020-01-07 15:12
I'm going to close this thread as it is not a doc related issue. The product team has acknowledged the bug in the product repo and you can subscribe to that thread for updates: https://github.com/Azure/azure-cli/issues/11767

The command works without the --all flag, so that is the best workaround until the issue is addressed.

**Closed by SamaraSoucy-MSFT** 2020-01-07 15:12 UTC
Labels: Pri3
