### ISSUE TITLE
SpotRestorePolicy Error: "InvalidParameter"

### ISSUE THREAD

**Issue by Raphael1313** [MicrosoftDocs/azure-docs-cli#4474] opened 2024-07-22 10:33 UTC
### Type of issue

Code doesn't work

### Feedback

When using this example code (with changed values for Image and ResourceGroup) 

"az vmss create -n MyVmss -g MyResourceGroup  --location NorthEurope --instance-count 2 --image CentOS85Gen2 --priority Spot --eviction-policy Deallocate --single-placement-group --enable-spot-restore True --spot-restore-timeout PT1H"

I get the Error "DeploymentFailed" and the details: 

"code":"InvalidParameter","target":"spotRestorePolicy","message":"The value of parameter spotRestorePolicy is invalid."

(On Cloud-Shell with az --version = 2.62.0) 

### Page URL

https://learn.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vmss.yml

### Author

@dbradish-microsoft

### Document Id

852cb67b-70c6-b811-3b0a-5d5b84b8a911

**Comment by PesalaPavan** [comment] 2024-07-23 04:45
@Raphael1313 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment] 2024-07-24 19:59
Hello, @Raphael1313. An `invlalid parameter` is often caused by a missing or extra space in the reference syntax or missing quotes around parameter values. Looking at your description, it is missing a `true/false` value for the `single-placement-group`. Can you kindly provide a screen print of your syntax?

Here are two articles that use `az vmss create` and one of the `--%spot%` parameters:
1. https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/spot-priority-mix
2. https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/use-spot

**Comment by Raphael1313** [comment] 2024-07-24 21:17
Hello, 
I hope this helps. 

![Screenshot 2024-07-24 225302](https://github.com/user-attachments/assets/55a77569-6a1f-48ef-985a-91c7530d9674)

I also tried to set "--single-placement-group false --enable-spot-restore false" - this then worked and a vmss was deployed. 

(I also tried " --single-placement-group false --enable-spot-restore true" yielding the same invalid parameter response.)

**Comment by dbradish-microsoft** [comment] 2024-07-24 23:29
@Raphael1313 , Your screen print is very helpful and was enough information to move this GitHub issue to Azure/azure-cli where the engineering team for `az vmss` can respond to your feedback.  Please continue to followup in this new location.

**Closed by dbradish-microsoft** 2024-07-24 23:29 UTC
Labels: doc-bug, triaged, assigned-to-author, needs-triage, reference content

**Comment by dbradish-microsoft** [comment] 2024-10-15 03:51
@Raphael1313 , Please respond to the engineering team in Azure/azure-cli issue [29461](https://github.com/Azure/azure-cli/issues/29461).  Thank you.
