### ISSUE TITLE
Translated web pages do not work now which operated well previously

### ISSUE THREAD

**Issue by ianychoi** [MicrosoftDocs/azure-docs-cli#2338] opened 2020-12-10 16:33 UTC
Translated web pages had been published but they do not work currently, while seems that translations are being updated to corresponding repositories (e.g., https://github.com/MicrosoftDocs/azure-docs-cli.ja-jp - upload 7 hours ago, https://github.com/MicrosoftDocs/azure-docs-cli.ko-kr - uploaded 22 hours ago).

Would someone help to investigate in this? Let me share example of screenshots:

- English page ( https://docs.microsoft.com/en-us/cli/azure/install-azure-cli ): working very well
- Korean page ( https://docs.microsoft.com/ko-kr/cli/azure/install-azure-cli ): English page is shown with a message "This content is not in your language, but the English version is here."
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/6965982/101800431-9e0ce600-3b50-11eb-99e0-1f68b7958e65.png">

- Japanese page ( https://docs.microsoft.com/ja-jp/cli/azure/install-azure-cli ): English page is shown with a message "This content is not available in your language. The English version is here."
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/6965982/101800559-c09eff00-3b50-11eb-918d-5170a35ad3b9.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI](https://docs.microsoft.com/ko-kr/cli/azure/install-azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment] 2020-12-10 17:41
@ianychoi Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by ianychoi** [comment] 2021-03-03 21:17
@kobulloc-MSFT Any progress updates on this?

**Comment by kobulloc-MSFT** [comment] 2021-03-03 21:41
Adding @dbradish-microsoft for visibility.

**Comment by kobulloc-MSFT** [comment] 2021-04-09 16:06
@ianychoi I reached out to our localization team and they report that the ko-kr version of the page you linked is displaying as intended.  There have been changes to the loc feedback process so this request will have to go through the new channels:

On-demand feedback of localized content:
https://aka.ms/devrellocfeedback

Provide Feedback to DevRel Localization Team:
https://review.docs.microsoft.com/en-us/help/contribute/localization-feedback-to-loc-content

> **How do I respond to GitHub issues and public PRs in other languages/locales?**
> Going forward, DevRel Loc team will partner with other teams at Microsoft (e.g. subsidiaries, events, marketing, …) and focus on driving usage of the localized technical documentation. We will no longer make GitHub repos public for localized content due to this change. Any existing PRs and issues will be closed, with the exception of azure-docs, which will remain open for community contribution for human translated topics for 6 languages (Simplified Chinese, French, German, Japanese, Korean, Spanish). In addition, starting this summer, our localization pipeline will be updated and will no longer be based on GitHub repos, which will make the current community contribution process obsolete.
> 
> We still respond on-demands feedback of the localized content. Click https://aka.ms/devrellocfeedback to create ADO feedback ticket or refer details about Provide Feedback to DevRel Localization Team.

We are going to close this as resolved, but I would encourage you to reach out to the links that I've provided above.

**Closed by kobulloc-MSFT** 2021-04-09 16:06 UTC
Labels: Pri3, azure-cli/svc, cxp, doc-bug, triaged
