### ISSUE TITLE
what to do with private key from cert created by Azure CLI

### ISSUE THREAD

**Issue by stevenbrix** [MicrosoftDocs/azure-docs-cli#2501] opened 2021-03-30 22:50 UTC
I followed the instructions to create a service principal using Azure Key Vault like this:
```
az ad sp create-for-rbac --name <url> --create-cert --cert <cert-name> --keyvault <keyvault>
```

The docs then say to use the `az keyvault secret show` command to get the private key, which I did and saved it to a file that looks like this:

```
-----BEGIN RSA PRIVATE KEY-----
abcdefghijklmnopqrstuvwxyz012345678......
-----END RSA PRIVATE KEY------
```

But from there I'm not sure what to do. When I try to login with the key like this:

```
az login --service-principal -u <id> -tenant <tenantid> -p /path/to/cert.pem
```

I get the following error: 

```
Invalid certificate, please use a valid PEM file.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by Svijay-msft** [comment] 2021-03-31 06:01
Thanks for the question! We are taking a look into this and will get back to you soon.

**Comment by Svijay-msft** [comment] 2021-03-31 07:43
I tried steps mentioned in the document, unfortunately I was not able to reproduce the issue at my end. The below is the code I used to export the file in .PEM Format
```
$jsonresponse = $(az keyvault secret show --name Cert2 --vault-name svijay-KeyVault)
$json = ($jsonresponse | ConvertFrom-Json)
$Certificate = ($jsonresponse | ConvertFrom-Json).Value
$Certificate |Out-File -FilePath .\Certificate.pem
```

Also, In your question - I see you are seeing the RSA Private key - meaning it could be a different format certificate. 

Like the note suggests, a PEM certificate should contain Certificate and Private Key. 

![image](https://user-images.githubusercontent.com/66949976/113101926-eabd1f80-921a-11eb-8033-5d83f399da90.png)

Something similar to the below format : 

```
-----BEGIN PRIVATE KEY-----

MIIE..............

-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----

MIIDHjCCAgagAwIBAgIQDNI+TYkpSG+qWwna4/kglzANBgkqhkiG9.jA0NVowDDEK
MAgGA1............................

-----END CERTIFICATE-----


```

You could run the below file to understand what type of the content type. 

```
$jsonresponse = $(az keyvault secret show --name Cert1 --vault-name svijay-KeyVault)
$json = ($jsonresponse | ConvertFrom-Json)
$json.contentType
```
Output Observed at my end : 

![image](https://user-images.githubusercontent.com/66949976/113103979-95364200-921d-11eb-9b26-685c6b39d681.png)

If you see a different content type. This likely to be your cause.

**Comment by kobulloc-MSFT** [comment] 2021-04-05 23:33
@stevenbrix It looks like this has been resolved so we are going to close this thread as resolved but if there are any questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Closed by kobulloc-MSFT** 2021-04-05 23:33 UTC
Labels: Pri1, azure-cli/svc, cxp, product-question, triaged
