### ISSUE TITLE
gpg: keyserver receive failed: Server indicated a failure

### ISSUE THREAD

**Issue by baqwas** [MicrosoftDocs/azure-docs-cli#1286] opened 2019-02-12 00:11 UTC
On https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#signingKey at Step 3, I receive the following error message:

gpg: keyserver receive failed: Server indicated a failure

When I attempt to resolve the issue by clicking on the link at "make sure you have the latest signing key" I don't seem to be making any progress.

How can I resolve this issue, please?

chowkidar@BeUlta:/home/reza$ uname -a
Linux BeUlta 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#signingKey)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2019-02-19 20:35
Not the only report of the keyserver being down, will investigate. Likely a temporary issue.

**Comment by baqwas** [comment] 2019-02-19 22:41
OK. Thx.

P.S. I'm presently away for three weeks and will be able to read responses
but unable to retry until my return. Rgds.

**Comment by sptramer** [comment] 2019-02-20 00:07
Not able to reproduce the problem on a clean ubuntu install:

```
root@291c72d02316:/# sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
>      --keyserver packages.microsoft.com \
>      --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
Executing: /tmp/apt-key-gpghome.CFyJHTj64V/gpg.1.sh --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
gpg: key EB3E94ADBE1229CF: public key "Microsoft (Release signing) <gpgsecurity@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

If you can't reproduce the issue, please give some additional information about your configuration, including if you're located behind a firewall or proxy that may block keyserver traffic.

**Comment by sptramer** [comment] 2019-03-21 23:36
Closing due to lack of action, and the `apt` install instructions have been updated to avoid the use of `apt-key`.

**Closed by sptramer** 2019-03-21 23:36 UTC
Labels: needs-more-info, question, support-request, triaged

**Comment by baqwas** [comment] 2019-06-30 00:46
No issue encountered with a fresh install under Ubuntu 19.04! Had read the comment about apt-key and mercifully avoided it.
Many thanks for helping me to persist with VS Code.
