### ISSUE TITLE
Markdown for "With --only-show-errors" example breaks subsequent non-example documentation

### ISSUE THREAD

**Issue by zackste** [MicrosoftDocs/azure-docs-cli#4309] opened 2024-05-18 02:24 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

Latest

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/azure-cli-global-parameters?view=azure-cli-latest&tabs=tabid-2

### Description of the documentation error

The article's markdown is causing the `--subscription global parameter` and remaining parameter headings to be hidden behind the  `With --only-show-errors` tab.  This does not repro in the GitHub preview, but it shows on learn.microsoft.com .

This issue results in important, top-level information being buried inside an example's final sub-example, hiding the information from the user by default until the user clicks the sub-example tab.

Default when the page loads:
![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/4434856/7e2834ce-6404-474b-b78e-4b00449201ac)

After selecting the second example tab:
![image](https://github.com/MicrosoftDocs/azure-docs-cli/assets/4434856/205a186e-5831-4bc7-8b6a-58cc76ad0f98)

### Suggested fix

I'm not certain of the correct markdown here, but it may be that the example needs to be made another level or two deeper in the heading tree.
```diff
- # [With `--only-show-errors`](#tab/tabid-2)
+ ### [With `--only-show-errors`](#tab/tabid-2)
```

**Comment by PesalaPavan** [comment] 2024-05-18 16:11
@zackste 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment] 2024-05-20 03:58
@zackste 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by dbradish-microsoft** [comment] 2024-05-29 20:19
@zackste , Thank you for your clear description of the problem and your insight into the cause.  This has been corrected in [PR 4348](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4348).

Thank you for helping us to improve Azure CLI documentation.

**Closed by dbradish-microsoft** 2024-05-29 20:19 UTC
Labels: doc-bug, triaged, assigned-to-author, azure-cli/svc
