### ISSUE TITLE
[v2.26] az cli / acr purge crash: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by nulltoken** [MicrosoftDocs/azure-docs-cli#2659] opened 2021-07-12 15:00 UTC
This Azure Piepeline task was working fine in 2.25

```
      - task: AzureCLI@2
        displayName: Purge ancient Docker images
        inputs:
          azureSubscription: ${{ variables.serviceConnection }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az acr run --cmd "acr purge --filter '[REDACTED]:.*' --ago $(daysToKeepImages.howMany)d --untagged" --registry $(registryName) /dev/null
```

Since the update to 2.26, it now crashes with the following output

```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/run.py", line 93, in acr_run
    variant=platform_variant
TypeError: 'NoneType' object is not callable
To open an issue, please run: 'az feedback'
```

**Comment by SatishBoddu-MSFT** [comment] 2021-07-12 15:02
Hello @nulltoken What is the documentation link you have referred to in this case? Could you please provide that?

**Comment by SatishBoddu-MSFT** [comment] 2021-07-12 15:13
Hello @nulltoken 
I have assigned the issue to the content author for further review.

**Comment by nulltoken** [comment] 2021-07-12 15:32
@SatishBoddu-MSFT Thanks a lot!

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-07-12 16:57
@nulltoken Thanks for reaching out. I'd like to let you know that this channel (the [Azure CLI Docs](https://github.com/MicrosoftDocs/azure-docs-cli) repository) is only for driving improvements related to the [Azure CLI documentation](https://docs.microsoft.com/en-us/cli/azure/).

It looks like this issue is with the **Azure CLI Task** for Azure Pipelines. The right place to raise an issue with the CLI task would be the **azure-pipelines-tasks** repository. I'd request you to please create a bug report **[here](https://github.com/microsoft/azure-pipelines-tasks/issues/new)** with all the relevant details about your environment, agent, and error logs so the appropriate Team handling this task can check and fix.

Further, if you're able to reproduce this issue with the `acr purge` command on your local machine as well, it would be useful to have the Azure CLI engineering team investigate it. To provide feedback about the issue from the command line itself, try the `az feedback` command from your machine.

At this point, it appears that there are no edits or updates needed to the CLI docs. Hence closing this issue for now. If there are any further questions regarding the Azure CLI documentation, please tag me in your reply and we will be happy to continue the conversation. Thanks again for your understanding.

**Closed by BhargaviAnnadevara-MSFT** 2021-07-12 16:57 UTC
Labels: Pri3, azure-cli/svc, cxp, product-bug, triaged
