### ISSUE TITLE
Package name is incorrect

### ISSUE THREAD

**Issue by swieder** [MicrosoftDocs/azure-docs-cli#1407] opened 2019-04-12 15:51 UTC
Believe this statement:

sudo apt-get install curl apt-transport-https lsb-release gpg

Should be 

sudo apt-get install curl apt-transport-https lsb-release gnupg

The gpg package name is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2019-04-23 19:50
@swieder The `gpg` package is available on the versions of Ubuntu that I tested - which distribution are you using that requires `gnupg`?

**Comment by sptramer** [comment] 2019-04-23 19:50
This is a duplicate of #1397 which includes information on the distribution, closing.

**Closed by sptramer** 2019-04-23 19:50 UTC
Labels: needs-more-info, triaged
