### ISSUE TITLE
az login command failed when executed through Terraform (remote-exec)

### ISSUE THREAD

**Issue by kzankpe** [MicrosoftDocs/azure-docs-cli#2857] opened 2021-12-03 09:16 UTC
# Describe the bug

Command Name
```az login```

Errors Message:
```
The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 5] : ''
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 145, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 160, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 147, in login_with_service_principal
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1589, in acquire_token_for_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 735, in obtain_token_for_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 771, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 523, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 184, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 49, in modify
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/persistence.py", line 163, in save
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 82, in protect
PermissionError: [WinError 5] : ''
```

# To Reproduce:
The installation and command execution is done through Terraform (remote-exec).
The powershell script content:

```
$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi

Start-Sleep -s 10

az login --service-principal -u $user -p $pass --tenant $tenantid
```

# Expected Behavior

# Environment Summary
 ```
Windows Server 2019 Standard 64bit
azure-cli                         2.30.0
 core                              2.30.0
 telemetry                          1.0.6
```
# Additional Context

I don't get errors when the same script is executed on the instance directly when using remote desktop.
The user account is the same used in the Terraform script (remote-exec).

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-12-03 10:08
@kzankpe Thanks for reaching out. It seems like you're running into issues executing the `az login` command.

Since the issue is around behavior of specific Azure CLI commands, it would be best addressed in the [Azure/azure-cli](https://github.com/Azure/azure-cli/) repository. I'd request you to please create a bug report **[here](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=&template=Bug_report.md&title=)** with all the relevant details about your environment and error logs so our Engineering Team can check and fix. Please run the `az feedback` command from your local machine and add the generated template to the GitHub issue to add the complete error details.

We will now proceed to close this thread as this channel (the [Azure CLI Docs](https://github.com/MicrosoftDocs/azure-docs-cli) repository) is only for driving improvements related to the [Azure CLI documentation](https://docs.microsoft.com/en-us/cli/azure/). However, if there are any further questions regarding the Azure CLI docs, please tag me in your reply and we will be happy to continue the conversation.

**Closed by BhargaviAnnadevara-MSFT** 2021-12-03 10:08 UTC
Labels: triaged, product-bug, azure-cli/svc, Pri3, cxp

**Comment by kzankpe** [comment] 2021-12-03 10:28
@BhargaviAnnadevara-MSFT Thank you for your response.
