### ISSUE TITLE
SSL handshake error on using az universal package publish

### ISSUE THREAD

**Issue by goutam1206** [MicrosoftDocs/azure-docs-cli#2826] opened 2021-11-14 11:21 UTC
Hello Team,

I'm using az cli version 2.8.0, and facing SSL Handshake errors while publishing a universal package to my organization's feed.

I'd like to mention that, the path in the exception thrown (C:\Users\VSSADM~1\) is something not a specific path to my machine. Would like to know, if this is a defect on the az cli ? Please do let me know, as it is a blocker for me, or please direct me to do this activity appropiately

```
The command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='274vsblobprodsin130.vsblob.vsassets.io', port=443): Max retries exceeded with url: /artifacttool/artifacttool-win10-x64-Release_0.2.198.zip?sv=2019-07-0
b&sig=higoj5xPr7xVIu5mvUYfsBFOUe5fCl8I5XHwEGncGa8%3D&spr=https&se=2021-11-14T11%3A43%3A25Z&sp=r&P1=1636889905&P2=11&P3=2&P4=Ff2V3QgsxcZxOE7Vam%2fjWpxaxM411Li6NHlO%2bmt8amM%3d (Ca
by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\contrib\pyopenssl.py", line 456, in wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\pyOpenSSL\OpenSSL\SSL.py", line 1915, in do_handshake
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\pyOpenSSL\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\connection.py", line 344, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\util\ssl_.py", line 347, in ssl_wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\contrib\pyopenssl.py", line 462, in wrap_socket
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-aq7acbhx\urllib3\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='274vsblobprodsin130.vsblob.vsassets.io', port=443): Max retries exceeded with url: /artifacttool/artifacttool-win10-x6
ease_0.2.198.zip?sv=2019-07-07&sr=b&sig=higoj5xPr7xVIu5mvUYfsBFOUe5fCl8I5XHwEGncGa8%3D&spr=https&se=2021-11-14T11%3A43%3A25Z&sp=r&P1=1636889905&P2=11&P3=2&P4=Ff2V3QgsxcZxOE7Vam%2
axM411Li6NHlO%2bmt8amM%3d (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\knack\knack\cli.py", line 215, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 709, in _run_job
  File "C:\Users\gmylavarapu\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\six\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\__init__.py", line 545, in default_command_handler
  File "C:\Users\gmylavarapu\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 56, in publish_package
    return artifact_tool.publish_universal(organization, project, feed, name, version, description, path)
  File "C:\Users\gmylavarapu\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 54, in publish_universal
    return self.run_artifacttool(organization, args, "Publishing")
  File "C:\Users\gmylavarapu\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 58, in run_artifacttool
    artifacttool_dir = self._artifacttool_updater.get_latest_artifacttool(organization)
  File "C:\Users\gmylavarapu\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool_updater.py", line 43, in get_latest_artifacttool
    artifacttool_binary_path = self._get_artifacttool(organization)
  File "C:\Users\gmylavarapu\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool_updater.py", line 74, in _get_artifacttool
    _update_artifacttool(release_uri, release_id)
  File "C:\Users\gmylavarapu\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool_updater.py", line 98, in _update_artifacttool
    response = requests.get(uri, stream=True)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\requests\requests\api.py", line 75, in get
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\requests\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\requests\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='274vsblobprodsin130.vsblob.vsassets.io', port=443): Max retries exceeded with url: /artifacttool/artifacttool-win10-x64-Re
_0.2.198.zip?sv=2019-07-07&sr=b&sig=higoj5xPr7xVIu5mvUYfsBFOUe5fCl8I5XHwEGncGa8%3D&spr=https&se=2021-11-14T11%3A43%3A25Z&sp=r&P1=1636889905&P2=11&P3=2&P4=Ff2V3QgsxcZxOE7Vam%2fjWp
11Li6NHlO%2bmt8amM%3d (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

To open an issue, please run: 'az feedback'
```

Thanks and regards,
Goutama

**Comment by BhargaviAnnadevara-MSFT** [comment] 2021-11-14 16:03
@goutam1206 Thanks for reaching out. It seems like you're running into an issue executing the [az artifacts universal publish](https://docs.microsoft.com/en-us/cli/azure/artifacts/universal?view=azure-cli-latest#az_artifacts_universal_publish) command. I couldn't help but notice that the version you currently have installed, `2.8.0` is pretty old, and could be worth upgrading to the latest version `2.30.0`, unless you are bound by this specific version of Azure CLI.

Since the issue is around behavior of specific Azure CLI commands, it would be best addressed in the [Azure/azure-cli](https://github.com/Azure/azure-cli/) repository. Please run the `az feedback` command from your local machine and add the generated template to the GitHub issue to add the complete error details along with your environment details.

We will now proceed to close this thread as this channel (the [Azure CLI Docs](https://github.com/MicrosoftDocs/azure-docs-cli) repository) is only for driving improvements related to the [Azure CLI documentation](https://docs.microsoft.com/en-us/cli/azure/). However, if there are any further questions regarding the Azure CLI docs, please tag me in your reply and we will be happy to continue the conversation.

**Closed by BhargaviAnnadevara-MSFT** 2021-11-14 16:03 UTC
Labels: triaged, needs-more-info, product-bug, azure-cli/svc, Pri3, cxp

**Comment by goutam1206** [comment] 2021-11-15 03:29
Thank you @BhargaviAnnadevara-MSFT. Would do the appropriate
