### ISSUE TITLE
 The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by ehm-wehb** [MicrosoftDocs/azure-docs-cli#2256] opened 2020-10-27 16:33 UTC
I've researched this error and it typically only seemed to apply to people using unsupported releases.  I am using Ubuntu 18.04 on WSL.

I followed the guide here:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt

The error I get is when running an apt update is:
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**/etc/os-release:**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by ChaitanyaNaykodi-MSFT** [comment] 2020-10-28 00:15
Hello @ehm-wehb,  Thank you for your feedback! We will review and update as appropriate.

**Comment by HarshitaSingh-MSFT** [comment] 2020-11-02 11:17
Hello @ehm-wehb, after circling back to the doc owner, I got to know that this install process had come up a lot in Issues in the past. We either need our install to be enhanced and/or the doc to give more details.

I will try to get some conclusion on this internally and consequently keep you posted. Thanks in advance for understanding.

**Comment by HarshitaSingh-MSFT** [comment] 2020-11-02 23:03
Assigning this issue to @dbradish-microsoft to take this issue further.

**Comment by fengzhou-msft** [comment] 2020-11-05 02:50
The issue was caused by signing service delay in the Linux Repo and the `Release` file is not in sync with the latest package after the release. It has been resolved. Please try again.

The Linux Repo team is working on a new API to solve the file unsync issue.

**Comment by dbradish-microsoft** [comment] 2020-11-12 20:01
@ehm-wehb, were you able to follow-up on @fengzhou-msft 's comment to you on November 4th?

**Comment by ehm-wehb** [comment] 2020-11-19 16:10
@fengzhou-msft I just attempted this again, but get the same error.  I removed the azure repo and ran a:

curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

Unfortunately i then get a 
_E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' does not have a Release file._

**Comment by fengzhou-msft** [comment] 2020-11-20 06:33
@ehm-wehb I tried the command but cannot reproduce your issue. Can you simply run `sudo apt update && sudo apt install azure-cli -y` to see if you can refresh the repo and install azure-cli?

**Comment by josh-stevens** [comment] 2021-02-25 19:57
@fengzhou-msft Hello, I'm running Ubuntu 18.04 on WSL and I'm receiving this same error as of today.

**Comment by fengzhou-msft** [comment] 2021-02-26 04:20
@josh-stevens did you run `sudo apt update` first? The latest package should be fine, I just verified it on Ubuntu 18.04 WSL.

**Comment by cicorias** [comment] 2021-05-10 14:49
numerous `apt update` does not help.

I see the IP address changing so there is some round robin DNS in front of these servers -- but there is no success here.

This is Ubuntu 18.04 under WSL2.

```
➜  mmm-biceps sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                            
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                    
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                  
Ign:5 https://packages.microsoft.com/repos/azure-cli bionic InRelease              
Ign:6 https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic InRelease
Err:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
  Could not connect to packages.microsoft.com:443 (40.117.131.251), connection timed out [IP: 40.117.131.251 443]
Err:8 https://packages.microsoft.com/repos/azure-cli bionic Release
  Unable to connect to packages.microsoft.com:https: [IP: 40.117.131.251 443]
Err:9 https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic Release
  Unable to connect to packages.microsoft.com:https: [IP: 40.117.131.251 443]
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
➜  mmm-biceps sudo apt update
```

**Comment by jotolo** [comment] 2021-05-12 08:26
Receiving this error when trying to install `libreoffice`.
Does anyone know what the problem is? 

```
sudo add-apt-repository ppa:libreoffice/libreoffice-7-0 -y
Hit:1 http://mirror.hetzner.de/ubuntu/packages bionic InRelease00:01
Get:2 http://mirror.hetzner.de/ubuntu/packages bionic-updates InRelease [88.7 kB]00:01
Get:3 http://mirror.hetzner.de/ubuntu/packages bionic-backports InRelease [74.6 kB]00:01
Get:4 http://dl.google.com/linux/chrome/deb stable InRelease [1,811 B]00:01
Get:5 http://mirror.hetzner.de/ubuntu/packages bionic-security InRelease [88.7 kB]00:01
Hit:6 http://mirror.init7.net/ubuntu bionic InRelease00:01
Get:7 http://mirror.init7.net/ubuntu bionic-updates InRelease [88.7 kB]00:01
Hit:8 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease00:01
Hit:9 http://de.archive.ubuntu.com/ubuntu bionic InRelease00:01
Hit:10 https://baltocdn.com/helm/stable/debian all InRelease00:01
Hit:11 https://download.docker.com/linux/ubuntu bionic InRelease00:01
Hit:12 https://storage.googleapis.com/bazel-apt stable InRelease00:01
Get:13 http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease [6,780 B]00:01
Get:14 http://mirror.init7.net/ubuntu bionic-backports InRelease [74.6 kB]00:01
Get:15 http://de.archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]00:01
Hit:16 https://dl.yarnpkg.com/debian stable InRelease00:01
Get:17 http://mirror.init7.net/ubuntu bionic-security InRelease [88.7 kB]00:01
Hit:18 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease00:01
Hit:19 http://ppa.launchpad.net/cwchien/gradle/ubuntu bionic InRelease00:01
Get:20 http://de.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]00:01
Get:21 http://ppa.launchpad.net/libreoffice/libreoffice-7-0/ubuntu bionic InRelease [20.8 kB]00:01
Get:22 http://mirror.hetzner.de/ubuntu/packages bionic-updates/main i386 Packages [1,286 kB]00:01
Get:23 http://mirror.hetzner.de/ubuntu/packages bionic-updates/main amd64 Packages [2,068 kB]00:01
Hit:24 http://ppa.launchpad.net/pypy/ppa/ubuntu bionic InRelease00:01
Get:25 http://mirror.hetzner.de/ubuntu/packages bionic-updates/main Translation-en [413 kB]00:01
Get:26 http://mirror.hetzner.de/ubuntu/packages bionic-updates/restricted amd64 Packages [344 kB]00:01
Get:27 http://mirror.hetzner.de/ubuntu/packages bionic-updates/restricted Translation-en [46.8 kB]00:01
Get:28 http://mirror.hetzner.de/ubuntu/packages bionic-updates/universe i386 Packages [1,566 kB]00:01
Get:29 http://mirror.hetzner.de/ubuntu/packages bionic-updates/universe amd64 Packages [1,735 kB]00:01
Hit:30 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease00:01
Get:31 http://mirror.hetzner.de/ubuntu/packages bionic-updates/universe Translation-en [369 kB]00:01
Get:32 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,100 B]00:02
Get:33 http://mirror.hetzner.de/ubuntu/packages bionic-security/main i386 Packages [982 kB]00:02
Get:34 http://mirror.hetzner.de/ubuntu/packages bionic-security/main amd64 Packages [1,723 kB]00:02
Get:35 http://mirror.hetzner.de/ubuntu/packages bionic-security/main Translation-en [321 kB]00:02
Get:36 http://mirror.hetzner.de/ubuntu/packages bionic-security/restricted amd64 Packages [321 kB]00:02
Get:37 http://mirror.hetzner.de/ubuntu/packages bionic-security/restricted Translation-en [43.2 kB]00:02
Get:38 http://mirror.hetzner.de/ubuntu/packages bionic-security/universe i386 Packages [981 kB]00:02
Get:40 http://mirror.hetzner.de/ubuntu/packages bionic-security/universe amd64 Packages [1,125 kB]00:02
Get:41 http://mirror.hetzner.de/ubuntu/packages bionic-security/universe Translation-en [253 kB]00:02
Hit:39 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease00:02
Get:42 http://mirror.init7.net/ubuntu bionic-updates/main i386 Packages [1,286 kB]00:02
Get:43 http://packages.cloud.google.com/apt cloud-sdk-bionic/main i386 Packages [155 kB]00:02
Get:44 http://mirror.init7.net/ubuntu bionic-updates/main amd64 Packages [2,068 kB]00:02
Get:45 http://packages.cloud.google.com/apt cloud-sdk-bionic/main amd64 Packages [183 kB]00:02
Get:46 http://mirror.init7.net/ubuntu bionic-updates/main Translation-en [413 kB]00:02
Get:47 http://mirror.init7.net/ubuntu bionic-updates/restricted amd64 Packages [344 kB]00:02
Get:48 http://mirror.init7.net/ubuntu bionic-updates/restricted Translation-en [46.8 kB]00:02
Get:49 http://mirror.init7.net/ubuntu bionic-updates/universe i386 Packages [1,567 kB]00:02
Get:50 http://mirror.init7.net/ubuntu bionic-updates/universe amd64 Packages [1,735 kB]00:02
Get:51 http://mirror.init7.net/ubuntu bionic-updates/universe Translation-en [369 kB]00:02
Get:52 http://mirror.init7.net/ubuntu bionic-security/main i386 Packages [982 kB]00:03
Get:53 http://mirror.init7.net/ubuntu bionic-security/main amd64 Packages [1,723 kB]00:03
Get:54 http://mirror.init7.net/ubuntu bionic-security/main Translation-en [321 kB]00:03
Get:55 http://mirror.init7.net/ubuntu bionic-security/restricted amd64 Packages [321 kB]00:03
Get:56 http://mirror.init7.net/ubuntu bionic-security/restricted Translation-en [43.2 kB]00:03
Get:57 http://mirror.init7.net/ubuntu bionic-security/universe i386 Packages [981 kB]00:03
Get:58 http://mirror.init7.net/ubuntu bionic-security/universe amd64 Packages [1,125 kB]00:03
Get:59 http://mirror.init7.net/ubuntu bionic-security/universe Translation-en [253 kB]00:03
Get:60 http://de.archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1,723 kB]00:03
Get:61 http://de.archive.ubuntu.com/ubuntu bionic-security/main i386 Packages [982 kB]00:03
Get:62 http://de.archive.ubuntu.com/ubuntu bionic-security/main Translation-en [321 kB]00:03
Get:63 http://de.archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [321 kB]00:03
Get:64 http://de.archive.ubuntu.com/ubuntu bionic-security/restricted Translation-en [43.2 kB]00:03
Get:65 http://de.archive.ubuntu.com/ubuntu bionic-security/universe i386 Packages [981 kB]00:03
Get:66 http://de.archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,125 kB]00:03
Get:67 http://ppa.launchpad.net/libreoffice/libreoffice-7-0/ubuntu bionic/main i386 Packages [33.2 kB]00:03
Get:68 http://de.archive.ubuntu.com/ubuntu bionic-security/universe Translation-en [253 kB]00:03
Get:69 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,068 kB]00:03
Get:70 http://ppa.launchpad.net/libreoffice/libreoffice-7-0/ubuntu bionic/main amd64 Packages [33.2 kB]00:03
Get:71 http://de.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [1,286 kB]00:03
Get:72 http://de.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [413 kB]00:03
Get:73 http://ppa.launchpad.net/libreoffice/libreoffice-7-0/ubuntu bionic/main Translation-en [13.7 kB]00:03
Get:74 http://de.archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [344 kB]00:03
Get:75 http://de.archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [46.8 kB]00:03
Get:76 http://de.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,735 kB]00:03
Get:77 http://de.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [1,567 kB]00:03
Ign:78 https://packages.microsoft.com/repos/azure-cli bionic InRelease00:03
Get:79 http://de.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [369 kB]00:03
Err:80 https://packages.microsoft.com/repos/azure-cli bionic Release00:05
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.81.215.193 443]00:05
Reading package lists... Done00:09
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' no longer has a Release file.00:09
N: Updating from such a repository can't be done securely, and is therefore disabled by default.00:09
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by fchouina** [comment] 2021-06-22 13:28
This issue is still not resolved.
I had not encountered it in quite some time, but it reappeared between 2021-06-14 and 2021-06-22 and we are now unable to upgrade the packages from the azure-cli repo.

**/etc/os-release:**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

By disabling the azure-cli repo, we are able to keep our servers upgraded, but the Microsoft packages are not being upgraded.
Any news? 
Thanks!

**Comment by bonzaii** [comment] 2021-11-01 23:00
> Still same issue on fresh install of Ubuntu 21.10 on VirtualBox.
> 
> ```
> E: The repository 'https://packages.microsoft.com/repos/azure-cli impish Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> ```
> 
> ```
> └─$ cat /etc/apt/sources.list.d/azure-cli.list
> deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ impish main
> ```
> 
> ```
> └─$ cat /etc/os-release 
> PRETTY_NAME="Ubuntu 21.10"
> NAME="Ubuntu"
> VERSION_ID="21.10"
> VERSION="21.10 (Impish Indri)"
> VERSION_CODENAME=impish
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> UBUNTU_CODENAME=impish
> ```

My issue is resolved by using older version of the repository. The [Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) manual process of adding repo uses `AZ_REPO=$(lsb_release -cs)` to determine the Ubuntu version, which on newer versions will fail.

The "Install with one command" option forces "Focal" repo, which in my case is older than current mainstream version (impish).

I have resolved my problem using the Focal repo.

**Comment by SanderBlom** [comment] 2021-11-08 22:44
Same issue Pop OS 21.10.

`E: The repository 'https://packages.microsoft.com/repos/azure-cli impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

`
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

`

**Comment by branko111** [comment] 2022-01-04 20:22
ubuntu 20. still the same problem- any one  help?

E: The repository 'https://packages.microsoft.com/repos/... stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by jiasli** [comment] 2022-01-05 02:56
@branko111, the error message is trimmed to `...`. Could you share the full message?

**Comment by branko111** [comment] 2022-01-05 03:26
yes - this is the full message:
root@u1:~# apt update
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease              
Hit:2 http://au.archive.ubuntu.com/ubuntu focal InRelease                   
Hit:3 http://au.archive.ubuntu.com/ubuntu focal-updates InRelease                                          
Hit:4 http://au.archive.ubuntu.com/ubuntu focal-backports InRelease                                        
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                   
Ign:6 https://packages.microsoft.com/repos/... stable InRelease                         
Err:7 https://packages.microsoft.com/repos/... stable Release                           
  404  Not Found [IP: 20.188.102.6 443]
Reading package lists... Done      
E: The repository 'https://packages.microsoft.com/repos/... stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@u1:~#

**Comment by jiasli** [comment] 2022-01-05 03:33
Judging from these 2 line:

```
Ign:6 https://packages.microsoft.com/repos/... stable InRelease                         
Err:7 https://packages.microsoft.com/repos/... stable Release 
```

It seems your repo config is corrupted. It should like

```
$ cat /etc/apt/sources.list.d/azure-cli.list
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main
```

**Comment by branko111** [comment] 2022-01-05 10:40
Ubuntu 20.04.3 LTS probably it is corrupted when I enter this it gives me No such file or directory
root@u1:~# cat /etc/apt/sources.list.d/azure-cli.list
cat: /etc/apt/sources.list.d/azure-cli.list: No such file or directory
root@u1:~#

**Comment by jiasli** [comment] 2022-01-06 02:42
Could you check the content of `/etc/apt/sources.list.d/`?

```
ls /etc/apt/sources.list.d/
```

You may see https://wiki.debian.org/SourcesList for how to work with `sources.list`.

**Comment by branko111** [comment] 2022-01-06 07:51
yes
root@u1:~# ls /etc/apt/sources.list.d/
docker.list  docker.list.save
root@u1:~#

**Comment by jiasli** [comment] 2022-01-06 15:28
I am not sure where `https://packages.microsoft.com/repos/...` comes from.

Could you share the full steps you followed to reproduce this error? I cannot repro with a fresh docker image:

```
docker run -it --rm ubuntu:20.04

apt-get update
apt-get install ca-certificates curl apt-transport-https lsb-release gnupg --yes

curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    tee /etc/apt/sources.list.d/azure-cli.list

apt-get update
apt-get install azure-cli --yes
```

**Comment by branko111** [comment] 2022-01-07 03:47
after running  
docker run -it --rm ubuntu:20.04
apt update    - updates with no issues ( I dont need any package from ackages.microsoft.com -so I did not run rest or the suggested code)
now it updates with no issues- but my PC name was changed from original root@u1     to root@863c31e8baea 
Im not sure why ?

the rest - it looks no more issues 

root@u1:/etc/bind# docker run -it --rm ubuntu:20.04
Unable to find image 'ubuntu:20.04' locally
20.04: Pulling from library/ubuntu
ea362f368469: Pull complete 
Digest: sha256:b5a61709a9a44284d88fb12e5c48db0409cfad5b69d4ff8224077c57302df9cf
Status: Downloaded newer image for ubuntu:20.04
root@863c31e8baea:/# 
root@863c31e8baea:/# docker run -it --rm ubuntu:20.04
bash: docker: command not found
root@863c31e8baea:/# apt-get update
Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]            
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]  
Get:3 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [837 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1382 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [786 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]       
Get:11 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [855 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1812 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.7 kB]                  
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1118 kB]                    
Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [22.1 kB]                  
Get:18 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [50.8 kB]                      
Fetched 20.4 MB in 7s (2758 kB/s)                                                                          
Reading package lists... Done
root@863c31e8baea:/# 
root@863c31e8baea:/# apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease                                         
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease                                                   
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
root@863c31e8baea:/# docker 
bash: docker: command not found
root@863c31e8baea:/# docker --version
bash: docker: command not found
root@863c31e8baea:/# apt update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease                                                   
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease                                         
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
root@863c31e8baea:/# ^C
root@863c31e8baea:/# 
root@863c31e8baea:/# 





root@863c31e8baea:/# apt update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease                   
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
root@863c31e8baea:/#

**Comment by g-diwakar** [comment] 2022-01-28 12:24
My device has POP OS 21.10 installed . I am getting the following error.


Hit:1 http://apt.pop-os.org/proprietary impish InRelease                                     
Get:2 https://packages.microsoft.com/repos/azure-cli focal InRelease [10.4 kB]               
Hit:3 http://apt.pop-os.org/release impish InRelease                             
Get:4 https://packages.microsoft.com/repos/azure-cli focal/main amd64 Packages [7,892 B]
Hit:5 http://us.archive.ubuntu.com/ubuntu impish InRelease
Get:6 http://us.archive.ubuntu.com/ubuntu impish-security InRelease [110 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu impish-updates InRelease [110 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu impish-backports InRelease [101 kB]
Fetched 340 kB in 4s (77.5 kB/s)  
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.3.12~1637170272~21.10~312e7d7).
curl is already the newest version (7.74.0-1.3ubuntu2).
gnupg is already the newest version (2.2.20-1ubuntu4).
lsb-release is already the newest version (11.1.0ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 132 not upgraded.
Unable to find a package for your system. Please check if an existing package in https://packages.microsoft.com/repos/azure-cli/dists/ can be used in your system and install with the dist name: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo DIST_CODE=<dist_code_name> bash'
gdiwakar@pop-os:~$ sudo curl -sL https://aka.ms/InstallAzureCLIDeb | sudo DIST_CODE=<dist_code_name> bash

**Comment by jiasli** [comment] 2022-01-29 02:22
> now it updates with no issues- but my PC name was changed from original root@u1 to root@863c31e8baea
> Im not sure why ?

This is expected since `863c31e8baea` is the docker container's name. This question is irrelevant to Azure CLI.

**Comment by jiasli** [comment] 2022-01-29 02:23
@g-diwakar, I am afraid POP OS 21.10 is not supported.

**Comment by jiasli** [comment] 2022-01-29 02:26
In order not to bother other users and help us keep focused, if you have further questions, please create a new issue at https://github.com/Azure/azure-cli/issues.

**Closed by jiasli** 2022-01-29 02:26 UTC
Labels: triaged, assigned-to-author, product-question, awaiting-product-team-response, azure-cli/svc, Pri3, Linux

**Comment by bennettnw2** [comment] 2022-01-31 21:04
> 

I just wanted to say that this worked for me. I'm behind a corporate firewall and I copied the certificate to my WSL2 folder `/usr/local/share/ca-certificates` and then ran `sudo update-ca-certificates`. The output is below:

> $ sudo update-ca-certificates
Updating certificates in /etc/ssl/certs...
rehash: warning: skipping duplicate certificate in zscaler_root_ca.crt
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

Then the error `E: The repository 'https://packages.microsoft.com/repos/azure-cli focal Release' does not have a Release file.` no longer exists!

**Comment by Sinhraphathatron** [comment] 2022-03-05 06:53
I change the “AZ_REPO=$(lsb_release -cs)” to “AZ_REPO=stretch”. to make it work.

**Comment by alesrosina** [comment] 2023-11-30 14:31
Just a note for others:

If you check https://packages.microsoft.com/repos/azure-cli/dists/ you can see the list of repos. I'm on Ubuntu 23.10 and the latest supported Ubuntu is 22.04, so I had to change to `AZ_REPO=jammy`.

So whoever is responsible, please add a note in docs, which distros are supported by this script. Or change a script, to be a bit more robust.
