### ISSUE TITLE
az login --identity stopped working for Azure VM

### ISSUE THREAD

**Issue by E-RELevant** [MicrosoftDocs/azure-docs-cli#3160] opened 2022-05-29 06:23 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.36.0

### Link to affected document

https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli

### Description of the documentation error

It worked for a few days, then it stopped, dropping the following error:
![image](https://user-images.githubusercontent.com/20738487/170854975-83ee21b3-001d-4ff9-812f-f97dae7e6b34.png)

```azurecli-interactive
az login --identity
Failed to connect to MSI. Please make sure MSI is configured correctly and check the network connection.
Error detail: HTTPConnectionPool(host='xxx.xxx.xxx.xxx', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04E78B68>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
```

### Additional information:
The VM has System assigned identity enabled.
![image](https://user-images.githubusercontent.com/20738487/170855062-d2878ace-c898-4395-b56a-d8fa182dbdd6.png)

**Comment by shwetamathur7** [comment] 2022-05-30 00:36
Closing this issue as this is duplicate of https://github.com/MicrosoftDocs/azure-docs/issues/93623

**Closed** 2022-05-30 00:36 UTC
Labels: doc-bug, duplicate, triaged, Pri3, cxp
